.gitignore
backend/.env
backend/knexFile.js
backend/package.json
frontend/.env

Edit package.json ( change migrate to dev env instead of test env)
Remove test client (sqlite) inside knexfile
Add node env param to .env 
Remove .env from gitignore list

config BE to run with PG and Docker

---

backend/package.json
backend/yarn.lock
frontend/src/Components/Organisation/Search.js
frontend/src/Components/Organisation/index.js
frontend/src/Components/Organisation/search.css

Updated search by day and borough functionality to work with dynamic data, I changed search by service to search by borough because at the beginning was by borough and also by service was using the list of categories while the organisation already filtered by category

updated search by day and borough functionality to work perfectly

---

backend/yarn.lock
frontend/src/Components/Organisation/EditOrganisation.js
frontend/src/Components/Organisation/index.js

Updated eslint packages and remove Project at Tag duplication at edit an organisation component

fixed ci errors

---

backend/src/controllers/postInitialData.js
backend/src/routes/api.js
backend/src/routes/users.js
frontend/src/Components/Users/signUp/index.js

The errors were about  unhanded error at catch function so I handled that error at backend and also I add e.prevendDefault() function to handle submit function at singup component to make user signup successfully.

cached the errors at backend to fix server side issues

---

backend/db/migrations/20180308173243_create_all_tables.js
backend/src/authentication/passport.js
backend/src/controllers/users_controller.js
backend/src/model/Users.js
backend/src/routes/users.js
frontend/.env
frontend/src/Components/Categories/index.js
frontend/src/Components/LandingPage/landing-page.css
frontend/src/Components/LoginForm/LoginForm.js
frontend/src/Components/LoginForm/index.js
frontend/src/Components/LoginForm/login-form.css
frontend/src/Components/SideBar/index.js
frontend/src/Components/TopNav/index.js
frontend/src/Components/Users/forgot-password/forgotPassword.css
frontend/src/Components/Users/forgot-password/index.js
frontend/src/Components/Users/signUp/SignUpFields.js
frontend/src/Components/Users/signUp/index.js
frontend/src/Components/Users/signUp/signUp.css
frontend/src/Routes.js
frontend/src/actions/loginActions.js
frontend/src/helpers.js

=>Allow user to use email as username to login
=>Make related changes to login and signup, loginaction form in FE
=>Edit user schema, user api, passport.js, user controller

Use mail as username

---

frontend/src/Components/Organisation/index.js
frontend/src/Components/Users/signUp/signUp.css
frontend/src/helpers.js

Display organisation card in alphabetical order (asc)

Display organisation card alphabetically asc

---

frontend/src/Components/Organisation/OrganisationCard.js

displayed the distance at client side

fixed search by postcode issue

---

backend/src/controllers/get_controller.js

used then function instead of map, which was changed before because of that I did not checked it at before PR

used then function instead of map

---

frontend/src/Components/HomePage/HomeSearch.js
frontend/src/Components/Organisation/OrganisationCard.js
frontend/src/Components/Organisation/Search.js
frontend/src/Components/Organisation/index.css

=> Add unit: miles
=> Round distance to one decimal place

Improve UI for org-card component when it displays distance

---

backend/src/controllers/get_controller.js
frontend/src/Components/HomePage/HomePage.css
frontend/src/Components/HomePage/HomeSearch.js
frontend/src/helpers.js

added condition for getBranchesByPostcode API endpoint to return list of branches with postcode lat and long only or with categoryName, lat, and long.
added search by postcode field to home page search component and update search functionality.
updated getSuggestion function to display all suggest data with scroll bar.

Improve home page search component

---

frontend/src/Components/Organisation/OrganisationForm.js

Use static data to display categorie's name inside checkbox list to solve duplication issues

display static categories list on checkbox

---

frontend/src/Components/HomePage/HomeSearch.js
frontend/src/Components/Organisation/index.js
frontend/src/Components/Organisation/search.css

During search (by keyword and postcode) if there is postcode error you can't start new search (only by keyword) unless you refresh the page. The aim of this PR is to solve that issue and also display result of search by keyword even there is error for postcode search

Improve search functionality in home search

---

frontend/src/Components/Organisation/index.js

Handle case where day field value is Monday, Tuesday,  Wednesday, Thursday && Friday on search by day in a particular category

Handle case where day field info is Monday, Tuesday, ...  to Friday 

---

backend/src/controllers/postInitialData.js
script/data.js

fixed organisation duplication issue in organisation table,
added area as third part of duplication filter.

Fix duplication orgs issue

---

frontend/src/Components/Organisation/edit-org.css
frontend/src/Components/Organisation/index.css
frontend/src/Components/Organisation/single-org.css

Increase width of the single card org detail to remove scrolling effect so that user will not have to scroll when reading content of an input field.

Increase width of card detail org component to avoid scrolling to read info

---

frontend/src/Components/HomePage/HomeSearch.js
frontend/src/Components/Organisation/OrganisationCard.js
frontend/src/Components/Organisation/index.js

I added category to organisationCard in homeSearch component to let the user see the category of each card after the user get filtered result from the seach.

Add category to organisationCards in homeSearch component

---

frontend/src/Components/Organisation/SingleOrganisation.js

Make delete an organisation button visible only to admin

---

frontend/src/Components/HomePage/HomePage.css
frontend/src/Components/HomePage/HomeSearch.js

Fix style for Edit and Detail button in HomeSearch component

---

frontend/src/Components/Organisation/EditOrganisation.js
frontend/src/Components/Organisation/OrganisationForm.js

Cleaned the console errors at edit, add and organisationForm components.

Cleaned the console errors at edit, add and organisationForm components

---

frontend/src/Components/Organisation/single-org.css

Resize width of single org component and adjust padding to avoid disappearance of text

Resize of single org detail component

---

frontend/src/Components/Users/UsersListTable.js
frontend/src/Components/Users/user-table.css

Make arrow button (left and right) visible

Make arrow button of user table list visible 

---

backend/db/migrations/20180308173243_create_all_tables.js
backend/src/controllers/post_controller.js

Fix the bug of users not being able to edit organisations.

fix bug of not able to edit

---

frontend/src/Components/HomePage/HomePage.css
frontend/src/Components/HomePage/HomeSearch.js
frontend/src/Components/SideBar/index.js
frontend/src/Components/Users/UsersMenu.js
frontend/src/Components/Users/users.css

Add bug form link to the home page.
Rename logo to home
add feedback to sidebar

Add bug form's link to home page 

---

frontend/src/Components/Organisation/EditOrganisation.js
frontend/src/Components/Organisation/SingleOrganisation.js

> Add the print button in the details view.

Add the print button on the organizations details mode.

---

frontend/src/Components/HomePage/HomeSearch.js
frontend/src/Components/Users/UsersMenu.js

Update bug url

---

backend/src/routes/api.js
frontend/src/actions/getApiData.js

Encode & decode data 

---

frontend/src/Components/Users/UserDropDown.js

fix the img link

---

frontend/src/Components/Organisation/AddOrganisation.js

scroll to top in add org page
